stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  data_validation:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_validation.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_validation.py
      - artifacts/data_ingestion/Chicken-fecal-images
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/cnnClassifier/pipeline/stage_03_data_transformation.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_data_transformation.py
      - artifacts/data_ingestion/Chicken-fecal-images
      - config/config.yaml
    outs:
      - artifacts/data_transformation/transformed

  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_04_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/cnnClassifier/pipeline/stage_05_model_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_05_model_training.py
      - src/cnnClassifier/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_transformation/transformed
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_06_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_06_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/transformed
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
